name: docker-build-ci

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push new reference
        id: docker_build_reference
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO }}:${{ github.sha }}          
      -
        name: Image digest reference
        run: echo ${{ steps.docker_build_reference.outputs.digest }}
      -
        name: Build and push new latest
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO }}:latest                          
      -
        name: Image digest latest
        run: echo ${{ steps.docker_build_latest.outputs.digest }}